# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a63b3895258951f39f2fac03be3e062654c9d7e6bb14351fe38676b8c83e0a2dced14a8f39557959c0baf747fcd6bde09e8313d03c6c20858b09f5bb32ffba5

test:
  secret_key_base: b146adb293acbaca10dfbcb3ca00b203439ef176131f9463d0eca7d6f7b3e7525230003fbacfd764669f1d0db1a679f92f09ac9c6e43a892a3cafd5750a3b681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
